### PR TITLE
fix : updated height

### PR DESCRIPTION
**Pull request by prankurpandeyy**

### CODE REVIEW

**Comment by Sahil25061999** [comment]
overall code looks good to me.👍

**Comment by Naman-Saxena1** [comment]
This is very small change, no issues but you can add them in other PRs, I don't think you need to open separate PRs for such small changes. For now you can merge.

**Comment by rahulk31** [comment]
Good to merge Prankur 👍

**Review by varun1233 — APPROVED** [review]
Code looks good.

**Review by sri-rishi — APPROVED** [review]
Looks good to me for merging

**Pull request merged**
